export const blogStyles = ( theme ) => ({
  page: {
    background: theme.palette.background.default,
    minHeight: '100%',
    padding: theme.spacing(4, 3),
  },
  pageTitle: {
    fontSize: '2rem',
    fontWeight: 700,
    marginBottom: theme.spacing(4),
    color: theme.palette.text.primary,
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))',
    gap: theme.spacing(3),
  },
  card: {
    background: theme.palette.background.card,
    borderRadius: '16px',
    padding: theme.spacing(3),
    boxShadow: theme.palette.shadows.card,
    cursor: 'pointer',
    transition: 'transform 0.2s ease, box-shadow 0.2s ease',
    display: 'flex',
    flexDirection: 'column',
    gap: theme.spacing(1.5),
  },
  cardTitle: {
    fontSize: '1.2rem',
    fontWeight: 600,
    color: theme.palette.text.primary,
    margin: 0,
  },
  cardExcerpt: {
    fontSize: '0.9rem',
    color: theme.palette.text.secondary,
    lineHeight: 1.6,
    margin: 0,
    flex: 1,
  },
  cardMeta: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: theme.spacing(1),
  },
  cardDate: {
    fontSize: '0.78rem',
    color: theme.palette.text.secondary,
  },
  tagRow: {
    display: 'flex',
    gap: theme.spacing(0.75),
    flexWrap: 'wrap',
  },
  tag: {
    fontSize: '0.72rem',
    fontWeight: 600,
    padding: theme.spacing(0.25, 1),
    borderRadius: '99px',
    background: theme.palette.accent.chip,
    color: theme.palette.accent.chipText,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  // Single post view
  postPage: {
    background: theme.palette.background.default,
    minHeight: '100%',
    padding: theme.spacing(4, 3),
    maxWidth: '720px',
    margin: '0 auto',
  },
  backBtn: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    color: theme.palette.accent.main,
    fontWeight: 600,
    fontSize: '0.9rem',
    padding: theme.spacing(0.5, 0),
    marginBottom: theme.spacing(3),
    display: 'flex',
    alignItems: 'center',
    gap: theme.spacing(0.5),
  },
  postMeta: {
    display: 'flex',
    alignItems: 'center',
    gap: theme.spacing(1.5),
    flexWrap: 'wrap',
    marginBottom: theme.spacing(3),
    color: theme.palette.text.secondary,
    fontSize: '0.85rem',
  },
  markdownBody: {
    color: theme.palette.text.primary,
    lineHeight: 1.8,
    fontSize: '1rem',
  },
});
