export const aboutStyles = (theme) => ({
  page: {
    background: theme.palette.background.default,
    minHeight: '100%',
    padding: theme.spacing(4, 3),
    maxWidth: '1000px',
    margin: '0 auto',
  },
  heroContainer: {
    display: 'flex',
    gap: theme.spacing(4),
    alignItems: 'flex-start',
    marginBottom: theme.spacing(6),
    flexWrap: 'wrap',
  },
  heroContent: {
    flex: 1,
    minWidth: '300px',
  },
  profileImageContainer: {
    flexBasis: '250px',
    width: '250px',
    height: '250px',
    borderRadius: '16px',
    overflow: 'hidden',
    boxShadow: theme.palette.shadows.card,
    flexShrink: 0,
  },
  profileImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  heroTitle: {
    fontSize: '2.5rem',
    fontWeight: 700,
    color: theme.palette.text.primary,
    margin: theme.spacing(0, 0, 1, 0),
  },
  heroSubtitle: {
    fontSize: '1.1rem',
    color: theme.palette.text.secondary,
    margin: theme.spacing(0, 0, 2, 0),
    fontWeight: 500,
  },
  bioSection: {
    marginTop: theme.spacing(2),
  },
  sectionTitle: {
    fontSize: '1.5rem',
    fontWeight: 700,
    color: theme.palette.text.primary,
    marginBottom: theme.spacing(2),
    borderBottom: `2px solid ${theme.palette.accent.main}`,
    paddingBottom: theme.spacing(1),
  },
  bioText: {
    fontSize: '1rem',
    color: theme.palette.text.primary,
    lineHeight: 1.8,
    margin: 0,
  },
  cvSection: {
    marginBottom: theme.spacing(6),
  },
  cvCategory: {
    marginBottom: theme.spacing(3),
  },
  cvCategoryTitle: {
    fontSize: '1.1rem',
    fontWeight: 700,
    color: theme.palette.accent.main,
    margin: theme.spacing(0, 0, 1.5, 0),
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
  },
  cvItem: {
    paddingLeft: theme.spacing(2),
    borderLeft: `3px solid ${theme.palette.accent.main}`,
    marginBottom: theme.spacing(2),
    paddingBottom: theme.spacing(1.5),
  },
  cvItemHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: theme.spacing(0.5),
    gap: theme.spacing(1),
  },
  cvItemTitle: {
    fontSize: '1rem',
    fontWeight: 700,
    color: theme.palette.text.primary,
    margin: 0,
  },
  cvItemPeriod: {
    fontSize: '0.85rem',
    color: theme.palette.text.secondary,
    fontStyle: 'italic',
    whiteSpace: 'nowrap',
  },
  cvItemSubtitle: {
    fontSize: '0.95rem',
    fontWeight: 600,
    color: theme.palette.accent.main,
    margin: theme.spacing(0.25, 0),
  },
  cvItemDescription: {
    fontSize: '0.9rem',
    color: theme.palette.text.secondary,
    lineHeight: 1.6,
    margin: theme.spacing(0.5, 0, 0, 0),
  },
  socialSection: {
    marginTop: theme.spacing(6),
    marginBottom: theme.spacing(4),
    paddingTop: theme.spacing(4),
    borderTop: `1px solid ${theme.palette.accent.chip}`,
  },
  socialLinksContainer: {
    display: 'flex',
    gap: theme.spacing(2),
    justifyContent: 'flex-start',
    flexWrap: 'wrap',
  },
  socialButton: {
    display: 'flex',
    alignItems: 'center',
    gap: theme.spacing(1),
    padding: theme.spacing(1.5, 2.5),
    borderRadius: '12px',
    background: theme.palette.background.card,
    border: `2px solid ${theme.palette.accent.main}`,
    color: theme.palette.accent.main,
    cursor: 'pointer',
    textDecoration: 'none',
    fontWeight: 600,
    fontSize: '1rem',
    transition: 'transform 0.2s ease, box-shadow 0.2s ease',
    boxShadow: theme.palette.shadows.card,
  },
  socialIcon: {
    fontSize: '1.3rem',
    display: 'flex',
    alignItems: 'center',
  },
  socialLabel: {
    display: 'inline',
  },
});

